# Generated by Django 5.0.6 on 2024-06-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
