# Generated by Django 5.0.6 on 2024-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_quantity_cart_final_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
